name: Theme Check
on:
  push:
    branches:
      - main
      - development
      - juan-development
      - luis-development
      - staging-qa
      - uat
  pull_request:
    branches:
      - main
      - development
      - juan-development
      - luis-development
      - staging-qa
      - uat
jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '21.11.1'
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: npm install
      - name: Run Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.'
          base: ${{ github.event.pull_request && github.event.pull_request.base.ref || github.sha }}
