name: Theme Check
on: [push, pull_request]

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      actions: read 
      contents: read 
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 20.11  # Adjust based on your requirements
      - name: Install dependencies
        run: npm install
      - uses: shopify/theme-check-action@v2
        with:
          theme_root: '.'
          base: ${{ github.event.pull_request && github.event.pull_request.base.ref || github.sha }}
