# .github/workflows/theme-check.yml
name: Theme Check
on: [push,pull_request]
jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.' # optional, could be './dist'
          token: ${{ github.token }}
          base: main
